name: Java CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    # cache maven dependencies to stop redownload each time
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven

    - name: Lint
      run: ./mvnw checkstyle:check
      working-directory: user-service

    - name: Run tests
      env:
        API_KEY: ${{ github.ref == 'refs/heads/dev' && secrets.DEV_API_KEY || secrets.PROD_API_KEY }}
      run: |
        if [ -z "$API_KEY" ]; then
          echo "Missing API_KEY"
          exit 1
        fi
        ./mvnw clean test
      working-directory: user-service
